### ISSUE TITLE
DN -> S2 coefficients

### ISSUE THREAD

**Issue by lucabaldassarre** [sentinel-hub/natural-color#1]
Dear SentinelHub team,

were do the coefficients for the DN -> S2 conversion come from?
E.g., "return [0.986*B01, B02, 0.939*B03, 0.779*B04]".
Thank you for your answer.
Best regards,

Luca

**Comment by mkadunc** [comment]
The coefficients were obtained for each band by multiplying its spectral response curve with the spectrum of the D65 standard illuminant and integrating over all wavelengths.

Alternatively, these could be read from the Sentinel-2 product metadata files - see e.g. the tag `<Solar_Irradiance_List>` in [metadata for a product from January 2017](https://roda.sentinel-hub.com/sentinel-s2-l1c/products/2017/1/1/S2A_MSIL1C_20170101T001712_N0204_R116_T55LGH_20170101T001715/metadata.xml)

(depending on the shape of the sunlight spectrum and sensor response curves that were used in the calculation, you may get slightly different values for these coefficients in different metadata files)

Note that for use in the script, the coefficients have been scaled by dividing them with B02's coefficient to eliminate the difference in multiplicative gain between images...
