### ISSUE TITLE
DN Scaling?

### ISSUE THREAD

**Issue by gastoneb** [sentinel-hub/natural-color#2]
Hi, I'm trying to reproduce your aster_3x3_proper_gamma code in Python with rasterio and numpy. I'm wondering, is there a scaling of bands 2/3/4 (values 0-10000) applied before running your code? I don't know how it works in Sentinel Hub, e.g. if the band values have been scaled to 0-256 or something like that.

**Comment by mkadunc** [comment]
Hi, Sentinel-Hub scripts get TOA reflectance as input into variables B04, B03, B02 — if you're working with DNs, you should divide them by 10000 to get approx. range 0-1 (in exceptional cases it could go up to 6.5534).

The script is linear in input reflectances up to the point of final conversion to RGB, though, so you can adjust the `gain` factor to get an brighter or darker image (default is 2.5).

**Comment by gastoneb** [comment]
Thank you so much for the clarification. The gain adjustment works great now. On the unscaled DNs I was getting essentially greyscale outputs.
